In [23]:
import keras
import numpy as np
from LSTM import LSTMScratch
import pandas as pd
from Embedding import Embedding

In [ ]:
model = keras.models.Sequential()
model.add(keras.layers.LSTM(5))

X = np.random.rand(100, 10, 2)
y = np.random.rand(100, 1)

model.compile(optimizer="adam", loss="mse")
model.fit(X, y, epochs=1, batch_size=16)
pred = model.predict(X[:5])
print(pred)

7/7 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 0.4940
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 310ms/step
[[-0.07158522 -0.11916911 -0.11407842  0.15119088 -0.28053853]
 [-0.01608805 -0.07285324 -0.05957554  0.10027205 -0.1728075 ]
 [-0.07322105 -0.14025317 -0.18832186  0.16245425 -0.36477816]
 [-0.08132251 -0.13197604 -0.17220338  0.17878923 -0.34673566]
 [ 0.01765684 -0.13210237 -0.11241477  0.11871706 -0.27799574]]


In [27]:
weight = model.get_weights()

In [28]:
x = LSTMScratch(5, weight)

In [29]:
x.predict(X[:5])

[array([-0.07158523, -0.11916913, -0.11407846,  0.15119091, -0.28053849]),
 array([-0.01608803, -0.07285329, -0.05957554,  0.10027209, -0.1728076 ]),
 array([-0.07322106, -0.14025318, -0.1883219 ,  0.16245431, -0.3647782 ]),
 array([-0.0813225 , -0.13197604, -0.17220341,  0.17878925, -0.34673572]),
 array([ 0.01765685, -0.13210241, -0.11241481,  0.11871708, -0.27799571])]

In [ ]:
import tensorflow as tf

df = pd.read_csv("../dataset/rnn/test.csv")
x = df["text"]
y_text = df["label"]

vectorization = keras.layers.TextVectorization(
    max_tokens=1000, output_mode="int", output_sequence_length=5
)
vectorization.adapt(x)

x_vectorized = vectorization(tf.constant(x))

embed = Embedding(
    input_dim=len(vectorization.get_vocabulary()), output_dim=100
)

embedded_vectors = embed(x_vectorized)

lstm_layer = keras.layers.LSTM(5)
lstm_output = lstm_layer(embedded_vectors) 

print(lstm_output.numpy()[:5])

[[ 0.01738738  0.00054984 -0.00146147 -0.03523355  0.01071618]
 [ 0.01176027  0.01879282 -0.00843463  0.0197156   0.01719786]
 [-0.00590661 -0.00814146 -0.00543304  0.00350983  0.00876931]
 [ 0.00310229  0.01481104 -0.00084093  0.00147859  0.01081158]
 [ 0.02232325  0.00067978  0.01273542  0.00295634  0.02631428]]


In [31]:
scratch_lstm = LSTMScratch(5, lstm_layer.get_weights())
pred = scratch_lstm.predict(embedded_vectors)
pred[:5]

[array([ 0.01738738,  0.00054984, -0.00146146, -0.03523357,  0.01071619]),
 array([ 0.01176028,  0.01879283, -0.00843463,  0.01971561,  0.01719786]),
 array([-0.00590662, -0.00814145, -0.00543304,  0.00350983,  0.00876931]),
 array([ 0.00310229,  0.01481105, -0.00084093,  0.00147859,  0.01081158]),
 array([0.02232326, 0.00067978, 0.01273542, 0.00295634, 0.02631428])]