In [ ]:
import keras
import numpy as np
from lstm import LSTMScratch
import pandas as pd
from Layers.Embedding import Embedding

In [ ]:
import tensorflow as tf

df_train = pd.read_csv("../dataset/rnn/test.csv")
x_train = df_train["text"]
y_train = df_train["label"]

vectorization = keras.layers.TextVectorization(
    max_tokens=1000, output_mode="int", output_sequence_length=5
)
vectorization.adapt(x_train)

x_vectorized = vectorization(tf.constant(x_train))

embed = Embedding(
    input_dim=len(vectorization.get_vocabulary()), output_dim=100
)

embedded_vectors = embed(x_vectorized)

lstm_layer = keras.layers.LSTM(5)
lstm_output = lstm_layer(embedded_vectors) 

print(lstm_output.numpy()[:5])

[[ 0.01738738  0.00054984 -0.00146147 -0.03523355  0.01071618]
 [ 0.01176027  0.01879282 -0.00843463  0.0197156   0.01719786]
 [-0.00590661 -0.00814146 -0.00543304  0.00350983  0.00876931]
 [ 0.00310229  0.01481104 -0.00084093  0.00147859  0.01081158]
 [ 0.02232325  0.00067978  0.01273542  0.00295634  0.02631428]]


In [31]:
scratch_lstm = LSTMScratch(5, lstm_layer.get_weights())
pred = scratch_lstm.predict(embedded_vectors)
pred[:5]

[array([ 0.01738738,  0.00054984, -0.00146146, -0.03523357,  0.01071619]),
 array([ 0.01176028,  0.01879283, -0.00843463,  0.01971561,  0.01719786]),
 array([-0.00590662, -0.00814145, -0.00543304,  0.00350983,  0.00876931]),
 array([ 0.00310229,  0.01481105, -0.00084093,  0.00147859,  0.01081158]),
 array([0.02232326, 0.00067978, 0.01273542, 0.00295634, 0.02631428])]

In [ ]:
# model = keras.models.Sequential()
# model.add(keras.layers.LSTM(5))

# X = np.random.rand(100, 10, 2)
# y = np.random.rand(100, 1)

# model.compile(optimizer="adam", loss="mse")
# model.fit(X, y, epochs=1, batch_size=16)
# pred = model.predict(X[:5])
# print(pred)

# weight = model.get_weights()
# x = LSTMScratch(5, weight)
# x.predict(X[:5])